name: Build and tests

on:
    push:
      branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 14.20.0
        uses: actions/setup-node@v3
        with:
          node-version: '14.20.0'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: npm run build

